language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t tenzan/frontend-app -f Dockerfile.dev .

script:
    - docker run -e CI=true tenzan/frontend-app npm run test